OpenLayers.Util.applyDefaults(OpenLayers.Lang["fr"], {    
    "sol.group": "Hydrologie",
    "sol.wpsbvtitle": "Contour de Bassin Versant",
    "sol.wpsbvabstract": "Affiche le Bassin Versant a l'amont de point(s) sélectonné(s)",
    "sol.error": "Message d'erreur du logiciel MNTSurf",
    "sol.impossible": "Pas possible ici",	  
    "sol.execute": "Calcul en cours...",      
    "sol.parameterstool": "Paramètres de l'outil bassin versant",
    "sol.error1": "Un maximum de 10000 entités est géré dans l'outil. La couche importée en contient",
    "sol.error2": "les entités ne sont pas de type POINT",
    "sol.error3": "Absence de sélection dans le requêteur",
    "sol.error4": "ce type de fichier ne peut être chargé",
    "sol.error5": "Aucune donnée dans le fichier GML",
    "sol.nopointlayer": "Aucune couche utilisable, ajoutez d'abord une couche vecteur de type POINT",
    "sol.fileselection": "Sélection d'un fichier gml",
    "sol.file": "Fichier",
    "sol.getucsfromclick": "Cliquer sur la carte",
    "sol.bvfromselection": "Calcul BV depuis sélection",
    "sol.bvfromselectiontip":"Calcul BV depuis sélection",
    "sol.bvfromcover": "Calcul BV depuis couche WMS",
    "sol.bvfromcovertip":"Calcul du contour du bassin versant depuis couche WMS",
    "sol.loadgml": "Charger un fichier gml.",
    "sol.loadgmltip": "Charger un fichier gml.",
    "sol.parameters": "Paramètres",
    "sol.parameterstip": "Paramètres",
    "sol.zoomToResultLayer": "Zoomer sur la couche produite"
});
OpenLayers.Util.applyDefaults(OpenLayers.Lang["en"], {    
    "sol.group": "Hydrology",
    "sol.wpsbvtitle": "Edge Catchment",
    "sol.wpsbvabstract": "Calculate edge catchemnt upstream of point(s)",
    "sol.error": "MNTSurf tool error",
    "sol.impossible": "Not possible here",	  
    "sol.refresh": "Refresh",
    "sol.execute": "Processing...",      
    "sol.parameterstool": "Watershed tool parameters",
    "sol.error1": "A max of 10000 features is managed in the profile tool. The imported layer contains",
    "sol.error2": "Only Point geometry is managed",
    "sol.error3": "No selection in querier !",
    "sol.error4": "This file type can't be loaded",
    "sol.error5": "No data In GML file",
    "sol.nopointlayer": "no useful layer loaded, add  POINT type layer before",
    "sol.fileselection": "gml file selection",
    "sol.file": "File",
    "sol.getucsfromclick": "Click on the map",
    "sol.bvfromselection": "Catchment calculation from selection",
    "sol.bvfromselectiontip":"Catchment calculation from selection",
    "sol.bvfromcover": "Catchment calculation from WMS cover",
    "sol.bvfromcovertip": "Catchment calculation from WMS cover",
    "sol.loadgml": "Load gml file.",
    "sol.loadgmltip": "Load gml file.",
    "sol.parameters": "Parameters",
    "sol.parameterstip": "Parameters",  
    "sol.zoomToResultLayer": "Zoom to result layer"
});


